// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class JobSeekerProfile
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Bio { get; set; }

    public string Skills { get; set; }

    public int? ExperienceYears { get; set; }

    public string ResumeUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    public virtual User User { get; set; }
}